import argparse
import csv
import io
from pathlib import Path


LEVELS = [
    {
        "id": "a0_survival",
        "name": "A0 - Survival",
        "goal": "Recognize Spanish sentence shape, gender, number, and the first core verbs.",
        "topics": [
            "pronunciation and accent marks",
            "noun gender",
            "plural nouns",
            "adjective agreement",
            "subject pronouns",
            "ser basics",
            "negation",
            "yes-no questions",
        ],
    },
    {
        "id": "a1_1_foundations",
        "name": "A1.1 - Foundations",
        "goal": "Build simple present-tense sentences about identity, location, and routine.",
        "topics": [
            "ser vs estar",
            "regular -ar present",
            "regular -er and -ir present",
            "articles",
            "hay",
            "question words",
        ],
    },
    {
        "id": "a1_2_core_sentences",
        "name": "A1.2 - Core Sentences",
        "goal": "Talk about needs, plans, likes, possession, and basic objects.",
        "topics": [
            "tener and tener que",
            "ir a infinitive",
            "possessive adjectives",
            "gustar basics",
            "reflexive verbs",
            "direct object pronouns",
        ],
    },
    {
        "id": "a2_1_daily_past",
        "name": "A2.1 - Daily Past & Comparison",
        "goal": "Talk about completed events, background situations, comparisons, and simple commands.",
        "topics": [
            "regular preterite",
            "irregular preterite",
            "imperfect basics",
            "preterite vs imperfect",
            "comparatives",
            "informal commands",
        ],
    },
    {
        "id": "a2_2_natural_spanish",
        "name": "A2.2 - More Natural Spanish",
        "goal": "Connect ideas and avoid English-shaped Spanish in common A2 structures.",
        "topics": [
            "por vs para",
            "indirect object pronouns",
            "double object pronouns",
            "present progressive",
            "present perfect",
            "relative clauses and connectors",
        ],
    },
]


TOPICS = [
    {
        "level": "a0_survival",
        "topic": "pronunciation and accent marks",
        "formula": "á, é, í, ó, ú mark stressed vowels; ñ is a separate sound; h is silent.",
        "use": "Use accent marks and special letters as part of spelling, not decoration.",
        "examples": ["sí = yes", "si = if", "año = year", "hablo = I speak"],
        "trap": "ano without ñ is a different word. Keep ñ.",
        "choose": ("Choose: year<br>A) ano<br>B) año", "B) año", "ñ changes the sound and the meaning."),
        "correction": ("Si, estudio espanol.", "Sí, estudio español.", "Accent marks matter: sí = yes; español has ñ."),
        "production": ("Write in Spanish: Yes, I speak Spanish.", "Sí, hablo español.", "This uses sí with an accent and español with ñ."),
        "pattern": ("sí/no answer", "Sí, + sentence. / No, + sentence.", ["Sí, estudio.", "No, trabajo.", "Sí, hablo español."]),
    },
    {
        "level": "a0_survival",
        "topic": "noun gender",
        "formula": "el + masculine noun; la + feminine noun",
        "use": "Every Spanish noun has grammatical gender. Learn the article with the noun.",
        "examples": ["el libro", "la casa", "el problema"],
        "trap": "Many -a words are feminine, but el problema is masculine.",
        "choose": ("Choose: ___ libro<br>A) el<br>B) la", "A) el libro", "libro is masculine."),
        "correction": ("la problema", "el problema", "problema ends in -a but is masculine."),
        "production": ("Write in Spanish: the house", "la casa", "casa is feminine."),
        "pattern": ("article + noun", "el/la + noun", ["el libro", "la mesa", "el mapa"]),
    },
    {
        "level": "a0_survival",
        "topic": "plural nouns",
        "formula": "vowel + s; consonant + es",
        "use": "Make nouns plural according to their ending.",
        "examples": ["libro -> libros", "casa -> casas", "ciudad -> ciudades"],
        "trap": "The article changes too: el libro -> los libros.",
        "choose": ("Choose: two cities = dos ___<br>A) ciudad<br>B) ciudades", "B) dos ciudades", "A consonant-ending noun often adds -es."),
        "correction": ("los ciudad", "las ciudades", "ciudad is feminine; plural is ciudades."),
        "production": ("Write in Spanish: the books", "los libros", "el becomes los and libro becomes libros."),
        "pattern": ("plural article + noun", "los/las + plural noun", ["los libros", "las casas", "las ciudades"]),
    },
    {
        "level": "a0_survival",
        "topic": "adjective agreement",
        "formula": "noun + adjective; adjective agrees in gender and number",
        "use": "Most descriptive adjectives come after the noun and match it.",
        "examples": ["el libro rojo", "la casa roja", "los libros rojos"],
        "trap": "Do not keep the masculine adjective for every noun.",
        "choose": ("Choose: la casa ___<br>A) rojo<br>B) roja", "B) la casa roja", "casa is feminine, so rojo becomes roja."),
        "correction": ("las casas rojo", "las casas rojas", "Feminine plural noun needs feminine plural adjective."),
        "production": ("Write in Spanish: the red books", "los libros rojos", "libros is masculine plural, so rojos."),
        "pattern": ("noun + color", "article + noun + color", ["el coche blanco", "la puerta blanca", "los coches blancos"]),
    },
    {
        "level": "a0_survival",
        "topic": "subject pronouns",
        "formula": "yo, tú, él/ella/usted, nosotros/nosotras, ellos/ellas/ustedes",
        "use": "Spanish verb endings often show the subject, so pronouns are often optional.",
        "examples": ["yo hablo", "tú estudias", "ella trabaja"],
        "trap": "usted means you formal but uses third-person verb forms.",
        "choose": ("Choose: informal singular you<br>A) tú<br>B) usted", "A) tú", "Use the informal singular pronoun, not the formal one."),
        "correction": ("usted hablas", "usted habla", "usted uses third-person singular verb forms."),
        "production": ("Write in Spanish: she", "ella", "Use the feminine third-person singular subject pronoun."),
        "pattern": ("optional subject", "(yo) hablo; (tú) estudias", ["Yo hablo.", "Hablo.", "Ella trabaja."]),
    },
    {
        "level": "a0_survival",
        "topic": "ser basics",
        "formula": "yo soy; tú eres; él/ella/usted es",
        "use": "Use ser for identity, origin, profession, and basic description.",
        "examples": ["Soy estudiante.", "Eres amable.", "Ella es médica."],
        "trap": "Do not use es with yo.",
        "choose": ("Choose: I am a student.<br>A) Soy estudiante.<br>B) Es estudiante.", "A) Soy estudiante.", "yo uses soy."),
        "correction": ("Yo es profesor.", "Yo soy profesor.", "The yo form of ser is soy."),
        "production": ("Write in Spanish: I am Ana.", "Soy Ana.", "Subject pronoun yo can be omitted."),
        "pattern": ("ser + identity", "soy/eres/es + noun/adjective", ["Soy estudiante.", "Eres Carlos.", "Es importante."]),
    },
    {
        "level": "a0_survival",
        "topic": "negation",
        "formula": "no + verb",
        "use": "Put no before the conjugated verb to make a sentence negative.",
        "examples": ["No soy médico.", "No estudio hoy.", "Ella no trabaja."],
        "trap": "Do not put no after the verb as in English short answers.",
        "choose": ("Choose: I am not a teacher.<br>A) No soy profesor.<br>B) Soy no profesor.", "A) No soy profesor.", "Spanish negation goes before the verb."),
        "correction": ("Soy no estudiante.", "No soy estudiante.", "Put no before soy."),
        "production": ("Write in Spanish: I do not study.", "No estudio.", "Use no before the verb."),
        "pattern": ("negative sentence", "no + conjugated verb", ["No hablo.", "No estudio.", "No es caro."]),
    },
    {
        "level": "a0_survival",
        "topic": "yes-no questions",
        "formula": "¿ + statement order + ?",
        "use": "Spanish yes-no questions can keep statement word order; intonation and punctuation mark the question.",
        "examples": ["¿Eres estudiante?", "¿Hablas español?", "¿Es importante?"],
        "trap": "Use the opening question mark in formal writing.",
        "choose": ("Choose: Do you speak Spanish?<br>A) ¿Hablas español?<br>B) Hablas español.", "A) ¿Hablas español?", "Question marks signal a written question."),
        "correction": ("Hablas español?", "¿Hablas español?", "Spanish uses opening and closing question marks."),
        "production": ("Write in Spanish: Do you speak Spanish?", "¿Hablas español?", "Statement order can become a question with punctuation/intonation."),
        "pattern": ("question from statement", "¿statement?", ["¿Estudias?", "¿Trabajas?", "¿Eres Ana?"]),
    },
    {
        "level": "a1_1_foundations",
        "topic": "ser vs estar",
        "formula": "ser = identity/essential description; estar = location/state",
        "use": "Choose ser for what something is and estar for where/how it is.",
        "examples": ["Soy estudiante.", "Estoy en casa.", "La puerta está abierta."],
        "trap": "Temporary feelings usually use estar: estoy cansado.",
        "choose": ("Choose: I am tired.<br>A) Soy cansado.<br>B) Estoy cansado.", "B) Estoy cansado.", "Tired is a state, so use estar."),
        "correction": ("Madrid está la capital de España.", "Madrid es la capital de España.", "Identity/role uses ser."),
        "production": ("Write in Spanish: I am at home.", "Estoy en casa.", "Location uses estar."),
        "pattern": ("ser/estar contrast", "ser + identity; estar + place/state", ["Es médico.", "Está aquí.", "Estoy bien."]),
    },
    {
        "level": "a1_1_foundations",
        "topic": "regular -ar present",
        "formula": "hablar: hablo, hablas, habla, hablamos, hablan",
        "use": "Use regular -ar endings for present habits and current facts.",
        "examples": ["Hablo español.", "Ella trabaja hoy.", "Estudiamos por la noche."],
        "trap": "The yo form ends in -o, not -a.",
        "choose": ("Choose: I speak Spanish.<br>A) Hablo español.<br>B) Habla español.", "A) Hablo español.", "yo form of hablar is hablo."),
        "correction": ("Yo habla español.", "Yo hablo español.", "The yo ending is -o."),
        "production": ("Write in Spanish: We study at night.", "Estudiamos por la noche.", "The nosotros form of estudiar is estudiamos."),
        "pattern": ("-ar present", "stem + o/as/a/amos/an", ["hablo", "hablas", "hablamos"]),
    },
    {
        "level": "a1_1_foundations",
        "topic": "regular -er and -ir present",
        "formula": "comer: como, comes, come; vivir: vivo, vives, vive",
        "use": "Use -er and -ir present endings for regular present-tense verbs.",
        "examples": ["Como arroz.", "Vivo en Madrid.", "Ella escribe mucho."],
        "trap": "-er and -ir differ in nosotros: -emos versus -imos.",
        "choose": ("Choose: I live in Mexico.<br>A) Vivo en México.<br>B) Vive en México.", "A) Vivo en México.", "yo form of vivir is vivo."),
        "correction": ("Ella comes arroz.", "Ella come arroz.", "Third-person singular of comer is come."),
        "production": ("Write in Spanish: I eat bread.", "Como pan.", "The yo form of comer is como."),
        "pattern": ("-er/-ir present", "stem + o/es/e/emos-en or imos-en", ["como", "vivo", "escribimos"]),
    },
    {
        "level": "a1_1_foundations",
        "topic": "articles",
        "formula": "definite: el/la/los/las; indefinite: un/una/unos/unas",
        "use": "Use definite articles for specific nouns and indefinite articles for nonspecific nouns.",
        "examples": ["un libro", "el libro", "unas casas", "las casas"],
        "trap": "Article gender and number must match the noun.",
        "choose": ("Choose: a house<br>A) un casa<br>B) una casa", "B) una casa", "casa is feminine singular."),
        "correction": ("el casas", "las casas", "Plural feminine noun needs las."),
        "production": ("Write in Spanish: some books", "unos libros", "libros is masculine plural."),
        "pattern": ("article agreement", "article + noun", ["un coche", "una mesa", "los problemas"]),
    },
    {
        "level": "a1_1_foundations",
        "topic": "hay",
        "formula": "hay + noun phrase",
        "use": "Use hay to say that something exists or is present.",
        "examples": ["Hay un libro.", "Hay tres personas.", "No hay tiempo."],
        "trap": "hay does not change for singular/plural.",
        "choose": ("Choose: There are two books.<br>A) Hay dos libros.<br>B) Hay dos libro.", "A) Hay dos libros.", "The noun becomes plural; hay stays the same."),
        "correction": ("Hay una problemas.", "Hay unos problemas.", "problemas is masculine plural."),
        "production": ("Write in Spanish: There is no time.", "No hay tiempo.", "Use no hay for there is not/there are not."),
        "pattern": ("existence", "hay + noun", ["Hay agua.", "Hay una mesa.", "Hay muchos libros."]),
    },
    {
        "level": "a1_1_foundations",
        "topic": "question words",
        "formula": "qué, quién, dónde, cuándo, cómo, cuánto/cuánta",
        "use": "Use question words to ask for specific information.",
        "examples": ["¿Qué estudias?", "¿Dónde vives?", "¿Cómo estás?"],
        "trap": "Question words normally carry accent marks.",
        "choose": ("Choose: Where do you live?<br>A) ¿Dónde vives?<br>B) ¿Qué vives?", "A) ¿Dónde vives?", "dónde asks where."),
        "correction": ("Donde vives?", "¿Dónde vives?", "Use accent and Spanish question marks."),
        "production": ("Write in Spanish: What do you study?", "¿Qué estudias?", "qué asks what."),
        "pattern": ("question word + verb", "¿question word + conjugated verb?", ["¿Qué comes?", "¿Dónde trabajas?", "¿Cuándo estudias?"]),
    },
    {
        "level": "a1_2_core_sentences",
        "topic": "tener and tener que",
        "formula": "tener + noun; tener que + infinitive",
        "use": "Use tener for possession/age and tener que for obligation.",
        "examples": ["Tengo un libro.", "Tengo veinte años.", "Tengo que estudiar."],
        "trap": "Age uses tener, not ser/estar.",
        "choose": ("Choose: I have to work.<br>A) Tengo que trabajar.<br>B) Tengo trabajar.", "A) Tengo que trabajar.", "Obligation needs tener que + infinitive."),
        "correction": ("Soy veinte años.", "Tengo veinte años.", "Spanish expresses age with tener."),
        "production": ("Write in Spanish: I have to study today.", "Tengo que estudiar hoy.", "Use tener que + infinitive."),
        "pattern": ("obligation", "tener que + infinitive", ["Tengo que salir.", "Tienes que leer.", "Tenemos que practicar."]),
    },
    {
        "level": "a1_2_core_sentences",
        "topic": "ir a infinitive",
        "formula": "ir a + infinitive",
        "use": "Use ir a + infinitive for near future plans.",
        "examples": ["Voy a estudiar.", "Vamos a comer.", "Ella va a viajar."],
        "trap": "Do not conjugate the second verb after a.",
        "choose": ("Choose: We are going to eat.<br>A) Vamos a comemos.<br>B) Vamos a comer.", "B) Vamos a comer.", "After a, keep the infinitive."),
        "correction": ("Voy a estudio.", "Voy a estudiar.", "Use infinitive after ir a."),
        "production": ("Write in Spanish: I am going to read.", "Voy a leer.", "voy a + infinitive."),
        "pattern": ("near future", "ir conjugated + a + infinitive", ["Voy a salir.", "Vas a estudiar.", "Van a trabajar."]),
    },
    {
        "level": "a1_2_core_sentences",
        "topic": "possessive adjectives",
        "formula": "mi/mis, tu/tus, su/sus, nuestro/nuestra/nuestros/nuestras",
        "use": "Possessive adjectives agree with the thing possessed.",
        "examples": ["mi libro", "mis libros", "nuestra casa"],
        "trap": "mi changes to mis for plural possessed nouns.",
        "choose": ("Choose: my books<br>A) mi libros<br>B) mis libros", "B) mis libros", "libros is plural, so use mis."),
        "correction": ("nuestra libros", "nuestros libros", "nuestro agrees with libros, masculine plural."),
        "production": ("Write in Spanish: your house", "tu casa", "tu is singular informal your."),
        "pattern": ("possessive + noun", "mi/tu/su + noun", ["mi casa", "tus amigos", "sus libros"]),
    },
    {
        "level": "a1_2_core_sentences",
        "topic": "gustar basics",
        "formula": "me/te/le gusta + singular or infinitive; me/te/le gustan + plural",
        "use": "gustar agrees with the thing liked, not the person who likes it.",
        "examples": ["Me gusta el café.", "Me gustan los libros.", "Nos gusta estudiar."],
        "trap": "Do not say yo gusto for I like something.",
        "choose": ("Choose: I like books.<br>A) Me gusta los libros.<br>B) Me gustan los libros.", "B) Me gustan los libros.", "The liked thing is plural: los libros."),
        "correction": ("Yo gusto café.", "Me gusta el café.", "Use me gusta for I like it."),
        "production": ("Write in Spanish: I like Spanish.", "Me gusta el español.", "The thing liked is singular."),
        "pattern": ("liking", "me gusta/gustan + thing", ["Me gusta leer.", "Te gusta el café.", "Le gustan las películas."]),
    },
    {
        "level": "a1_2_core_sentences",
        "topic": "reflexive verbs",
        "formula": "me/te/se/nos + reflexive verb",
        "use": "Use reflexive pronouns when the subject does the action to itself or for daily routines.",
        "examples": ["Me levanto temprano.", "Te llamas Ana.", "Se ducha por la mañana."],
        "trap": "The reflexive pronoun changes with the subject.",
        "choose": ("Choose: I get up early.<br>A) Me levanto temprano.<br>B) Se levanto temprano.", "A) Me levanto temprano.", "yo uses me."),
        "correction": ("Yo se llamo Luis.", "Yo me llamo Luis.", "The yo reflexive pronoun is me."),
        "production": ("Write in Spanish: I call myself Ana / My name is Ana.", "Me llamo Ana.", "llamarse is reflexive for names."),
        "pattern": ("daily routine", "reflexive pronoun + verb", ["Me despierto.", "Te levantas.", "Se lava."]),
    },
    {
        "level": "a1_2_core_sentences",
        "topic": "direct object pronouns",
        "formula": "lo/la/los/las replace direct objects",
        "use": "Use direct object pronouns to avoid repeating the object.",
        "examples": ["Veo el libro -> Lo veo.", "Compro la camisa -> La compro.", "Leo los mensajes -> Los leo."],
        "trap": "The pronoun agrees with the object, not the subject.",
        "choose": ("Choose: I see the house -> ___ veo.<br>A) Lo<br>B) La", "B) La veo.", "casa is feminine singular."),
        "correction": ("Veo la película. Lo veo.", "Veo la película. La veo.", "película is feminine singular, so la."),
        "production": ("Write in Spanish: I read it. (it = el libro)", "Lo leo.", "libro is masculine singular."),
        "pattern": ("object before verb", "lo/la/los/las + conjugated verb", ["Lo quiero.", "La veo.", "Los compro."]),
    },
    {
        "level": "a2_1_daily_past",
        "topic": "regular preterite",
        "formula": "-ar: é, aste, ó, amos, aron; -er/-ir: í, iste, ió, imos, ieron",
        "use": "Use preterite for completed past actions.",
        "examples": ["Hablé con Ana.", "Comí arroz.", "Vivimos en Lima durante dos años."],
        "trap": "Present yo hablo is not past; use hablé.",
        "choose": ("Choose: Yesterday I studied.<br>A) Ayer estudio.<br>B) Ayer estudié.", "B) Ayer estudié.", "Ayer signals a completed past action."),
        "correction": ("Ayer trabajo mucho.", "Ayer trabajé mucho.", "Use preterite for completed action yesterday."),
        "production": ("Write in Spanish: I ate bread yesterday.", "Ayer comí pan.", "comer in yo preterite is comí."),
        "pattern": ("completed past", "preterite verb + past time", ["Ayer hablé.", "Anoche comí.", "El lunes trabajé."]),
    },
    {
        "level": "a2_1_daily_past",
        "topic": "irregular preterite",
        "formula": "ir/ser: fui; tener: tuve; hacer: hice; decir: dije",
        "use": "Common high-frequency verbs have irregular preterite forms.",
        "examples": ["Fui al mercado.", "Tuve una reunión.", "Hice la tarea.", "Dije la verdad."],
        "trap": "fui can mean I went or I was; context decides.",
        "choose": ("Choose: I went to the store.<br>A) Fui a la tienda.<br>B) Iba a la tienda.", "A) Fui a la tienda.", "A completed trip uses preterite."),
        "correction": ("Yo tení una reunión.", "Yo tuve una reunión.", "tener has irregular preterite tuve."),
        "production": ("Write in Spanish: I did the work.", "Hice el trabajo.", "hacer in yo preterite is hice."),
        "pattern": ("common irregular past", "fui/tuve/hice/dije + object/place", ["Fui a casa.", "Tuve tiempo.", "Dije no."]),
    },
    {
        "level": "a2_1_daily_past",
        "topic": "imperfect basics",
        "formula": "-aba for -ar; -ía for -er/-ir; era/iba/veía are key irregulars",
        "use": "Use imperfect for background, habits, descriptions, age, and ongoing past states.",
        "examples": ["Cuando era niño, vivía en Madrid.", "Estudiaba cada noche.", "Tenía diez años."],
        "trap": "Age in the past often uses imperfect: tenía.",
        "choose": ("Choose: When I was a child<br>A) Cuando fui niño<br>B) Cuando era niño", "B) Cuando era niño", "Background identity/description in the past uses imperfect."),
        "correction": ("Cuando tuve diez años, vivía en Chile.", "Cuando tenía diez años, vivía en Chile.", "Age as background uses imperfect."),
        "production": ("Write in Spanish: I used to study every night.", "Estudiaba cada noche.", "Repeated past habit uses imperfect."),
        "pattern": ("past habit/background", "imperfect + repeated/background context", ["Vivía allí.", "Trabajaba mucho.", "Era difícil."]),
    },
    {
        "level": "a2_1_daily_past",
        "topic": "preterite vs imperfect",
        "formula": "preterite = completed event; imperfect = background/habit/ongoing state",
        "use": "Choose past tense based on how the speaker frames the action.",
        "examples": ["Estudiaba cuando llamaste.", "Ayer estudié dos horas.", "Era tarde cuando salimos."],
        "trap": "The same verb can use either tense with different meaning.",
        "choose": ("Choose: I was studying when you called.<br>A) Estudiaba cuando llamaste.<br>B) Estudié cuando llamabas.", "A) Estudiaba cuando llamaste.", "Ongoing background uses imperfect; interrupting event uses preterite."),
        "correction": ("Ayer estudiaba dos horas.", "Ayer estudié dos horas.", "A completed measured action uses preterite."),
        "production": ("Write in Spanish: It was raining when I arrived.", "Llovía cuando llegué.", "Background weather uses imperfect; arrival is preterite."),
        "pattern": ("background + event", "imperfect cuando preterite", ["Comía cuando llamaste.", "Dormía cuando llegué.", "Trabajaba cuando empezó."]),
    },
    {
        "level": "a2_1_daily_past",
        "topic": "comparatives",
        "formula": "más/menos + adjective + que; tan + adjective + como",
        "use": "Use comparatives to compare people, things, or situations.",
        "examples": ["Madrid es más grande que Toledo.", "Este libro es menos caro.", "Ana es tan alta como Luis."],
        "trap": "Do not use más mejor; mejor already means better.",
        "choose": ("Choose: better than<br>A) más mejor que<br>B) mejor que", "B) mejor que", "mejor is already comparative."),
        "correction": ("Este café es más bueno.", "Este café es mejor.", "Use mejor for better."),
        "production": ("Write in Spanish: This book is more expensive than that one.", "Este libro es más caro que ese.", "más + adjective + que."),
        "pattern": ("comparison", "más/menos/tan + adjective + que/como", ["más rápido que", "menos caro que", "tan fácil como"]),
    },
    {
        "level": "a2_1_daily_past",
        "topic": "informal commands",
        "formula": "tú affirmative often uses él/ella present form: habla, come, escribe",
        "use": "Use informal commands to tell one person to do something.",
        "examples": ["Habla despacio.", "Come algo.", "Escribe tu nombre."],
        "trap": "Common irregulars: ven, di, sal, haz, ten, ve, pon, sé.",
        "choose": ("Choose: Speak slowly.<br>A) Habla despacio.<br>B) Hablas despacio.", "A) Habla despacio.", "Affirmative tú command of hablar is habla."),
        "correction": ("Comes algo.", "Come algo.", "The command form is come, not comes."),
        "production": ("Write in Spanish: Write your name.", "Escribe tu nombre.", "Affirmative tú command of escribir is escribe."),
        "pattern": ("tú command", "verb command + object/adverb", ["Lee esto.", "Escucha.", "Mira aquí."]),
    },
    {
        "level": "a2_2_natural_spanish",
        "topic": "por vs para",
        "formula": "para = purpose/destination/deadline; por = cause/exchange/path/duration",
        "use": "Choose por or para by the relationship between ideas.",
        "examples": ["Trabajo para aprender.", "Gracias por tu ayuda.", "Salimos para Madrid.", "Caminé por el parque."],
        "trap": "English for maps to both por and para.",
        "choose": ("Choose: I study to learn.<br>A) Estudio por aprender.<br>B) Estudio para aprender.", "B) Estudio para aprender.", "Purpose/goal uses para."),
        "correction": ("Gracias para tu ayuda.", "Gracias por tu ayuda.", "Cause/reason for thanks uses por."),
        "production": ("Write in Spanish: This gift is for Ana.", "Este regalo es para Ana.", "Recipient/destination uses para."),
        "pattern": ("purpose/reason", "para + goal; por + reason", ["para estudiar", "por eso", "por la mañana"]),
    },
    {
        "level": "a2_2_natural_spanish",
        "topic": "indirect object pronouns",
        "formula": "me, te, le, nos, les + verb",
        "use": "Use indirect object pronouns for to/for whom something happens.",
        "examples": ["Le escribo a Ana.", "Me das el libro.", "Nos mandan un mensaje."],
        "trap": "le/les are often clarified with a + person.",
        "choose": ("Choose: I write to Ana.<br>A) Le escribo a Ana.<br>B) La escribo a Ana.", "A) Le escribo a Ana.", "Writing to someone uses an indirect object pronoun."),
        "correction": ("Lo doy el libro a Juan.", "Le doy el libro a Juan.", "Juan receives the book, so use le."),
        "production": ("Write in Spanish: She gives me the key.", "Ella me da la llave.", "me is the indirect object pronoun for to me."),
        "pattern": ("recipient", "indirect object pronoun + verb + thing", ["Te mando un mensaje.", "Le doy agua.", "Nos explica la regla."]),
    },
    {
        "level": "a2_2_natural_spanish",
        "topic": "double object pronouns",
        "formula": "indirect + direct object pronoun; le/les -> se before lo/la/los/las",
        "use": "Use double object pronouns to replace both recipient and thing.",
        "examples": ["Doy el libro a Ana -> Se lo doy.", "Mando la carta a Luis -> Se la mando.", "Te lo explico."],
        "trap": "Do not say le lo; change le to se.",
        "choose": ("Choose: I give it to her.<br>A) Le lo doy.<br>B) Se lo doy.", "B) Se lo doy.", "le becomes se before lo."),
        "correction": ("Le la mando.", "Se la mando.", "le/les change to se before la."),
        "production": ("Write in Spanish: I explain it to you.", "Te lo explico.", "Indirect pronoun comes before direct pronoun."),
        "pattern": ("two pronouns", "me/te/se/nos + lo/la/los/las + verb", ["Me lo das.", "Se la compro.", "Nos los envían."]),
    },
    {
        "level": "a2_2_natural_spanish",
        "topic": "present progressive",
        "formula": "estar + gerundio (-ando/-iendo)",
        "use": "Use present progressive for actions happening right now.",
        "examples": ["Estoy estudiando.", "Está comiendo.", "Estamos escribiendo."],
        "trap": "Spanish uses simple present more often than English for general/current plans.",
        "choose": ("Choose: I am studying right now.<br>A) Estoy estudiando ahora.<br>B) Soy estudiando ahora.", "A) Estoy estudiando ahora.", "Progressive uses estar, not ser."),
        "correction": ("Estoy estudio.", "Estoy estudiando.", "After estar, use the gerund."),
        "production": ("Write in Spanish: We are eating.", "Estamos comiendo.", "estar + -iendo."),
        "pattern": ("right now", "estar + -ando/-iendo", ["Estoy hablando.", "Está leyendo.", "Estamos trabajando."]),
    },
    {
        "level": "a2_2_natural_spanish",
        "topic": "present perfect",
        "formula": "haber + participle: he/has/ha/hemos/han + -ado/-ido",
        "use": "Use present perfect for recent or experience-related past with present relevance.",
        "examples": ["He visto la película.", "Hemos terminado.", "¿Has comido?"],
        "trap": "Do not insert words between haber and the participle in basic Spanish.",
        "choose": ("Choose: I have finished.<br>A) He terminado.<br>B) Soy terminado.", "A) He terminado.", "Present perfect uses haber."),
        "correction": ("He visto ayer la película.", "Vi la película ayer.", "Ayer is a finished-time expression; use preterite."),
        "production": ("Write in Spanish: Have you eaten?", "¿Has comido?", "has + participle."),
        "pattern": ("recent/experience past", "haber + participle", ["He llegado.", "Has leído.", "Hemos hablado."]),
    },
    {
        "level": "a2_2_natural_spanish",
        "topic": "relative clauses and connectors",
        "formula": "que/donde connect clauses; porque/pero/aunque connect ideas",
        "use": "Use connectors to make longer but still controlled Spanish sentences.",
        "examples": ["El libro que compré es bueno.", "La casa donde vivo es pequeña.", "Estudio porque quiero mejorar."],
        "trap": "que is often enough for who/that/which at this level.",
        "choose": ("Choose: the book that I bought<br>A) el libro que compré<br>B) el libro quien compré", "A) el libro que compré", "Use que for things."),
        "correction": ("La casa que vivo es pequeña.", "La casa donde vivo es pequeña.", "Use donde for where/in which."),
        "production": ("Write in Spanish: I study because I want to improve.", "Estudio porque quiero mejorar.", "porque gives the reason."),
        "pattern": ("connected sentence", "clause + connector + clause", ["Quiero salir, pero trabajo.", "Estudio porque quiero aprender.", "Es difícil aunque es útil."]),
    },
]


def _topic(level, topic, formula, use, examples, trap, choose, correction, production, pattern):
    return {
        "level": level,
        "topic": topic,
        "formula": formula,
        "use": use,
        "examples": examples,
        "trap": trap,
        "choose": choose,
        "correction": correction,
        "production": production,
        "pattern": pattern,
    }


TOPICS.extend(
    [
        _topic(
            "a1_1_foundations",
            "location prepositions",
            "encima de, debajo de, delante de, detrás de, al lado de, cerca de, lejos de",
            "Use location chunks with de to describe where things are.",
            ["El libro está encima de la mesa.", "La tienda está cerca de casa.", "Estoy al lado de Ana."],
            "Most location phrases need de before the reference noun.",
            ("Choose: The book is on the table.<br>A) El libro está encima la mesa.<br>B) El libro está encima de la mesa.", "B) El libro está encima de la mesa.", "encima de is the full location phrase."),
            ("Estoy cerca la escuela.", "Estoy cerca de la escuela.", "cerca needs de before the place."),
            ("Write in Spanish: The bank is next to the store.", "El banco está al lado de la tienda.", "al lado de means next to."),
            ("location chunk", "estar + location phrase + de + noun", ["Está detrás de la casa.", "Está lejos del centro.", "Está delante de mí."]),
        ),
        _topic(
            "a1_1_foundations",
            "ordinal basics",
            "primero/primer, segundo, tercero/tercer",
            "Use basic ordinal numbers for order.",
            ["el primer día", "la segunda clase", "el tercer libro"],
            "primero and tercero shorten before masculine singular nouns: primer, tercer.",
            ("Choose: the first day<br>A) el primero día<br>B) el primer día", "B) el primer día", "primero shortens to primer before masculine singular nouns."),
            ("el tercero libro", "el tercer libro", "tercero shortens to tercer before masculine singular nouns."),
            ("Write in Spanish: the second class", "la segunda clase", "segunda agrees with clase."),
            ("ordinal + noun", "primer/segundo/tercer + noun", ["el primer año", "la primera vez", "el tercer piso"]),
        ),
        _topic(
            "a1_2_core_sentences",
            "muy vs mucho",
            "muy + adjective/adverb; mucho/mucha/muchos/muchas + noun; verb + mucho",
            "Use muy for degree and mucho for quantity or action amount.",
            ["muy bueno", "mucho trabajo", "trabajo mucho"],
            "Do not put muy before nouns.",
            ("Choose: a lot of work<br>A) muy trabajo<br>B) mucho trabajo", "B) mucho trabajo", "Before a noun, use mucho/mucha."),
            ("Tengo muy libros.", "Tengo muchos libros.", "Use muchos with plural masculine nouns."),
            ("Write in Spanish: very interesting", "muy interesante", "muy modifies adjectives."),
            ("degree/quantity", "muy + adjective; mucho + noun/verb", ["muy fácil", "mucha agua", "estudio mucho"]),
        ),
        _topic(
            "a1_2_core_sentences",
            "todo and cada",
            "todo = all/every; cada = each/every individual",
            "Use todo with agreement and cada as invariable before singular nouns.",
            ["todos los días", "toda la semana", "cada día"],
            "cada does not become plural before a noun.",
            ("Choose: every day<br>A) cada día<br>B) cadas días", "A) cada día", "cada is invariable and takes singular noun."),
            ("todo los días", "todos los días", "todo agrees: todos los días."),
            ("Write in Spanish: all week", "toda la semana", "semana is feminine singular."),
            ("all/every", "todo/toda/todos/todas or cada + singular", ["todo el día", "todas las noches", "cada semana"]),
        ),
        _topic(
            "a2_1_daily_past",
            "obligation variants",
            "tener que; hay que; deber",
            "Use different obligation patterns for personal, general, and should-like obligation.",
            ["Tengo que estudiar.", "Hay que practicar.", "Debes descansar."],
            "hay que is general; it does not name the person.",
            ("Choose: One must practice.<br>A) Hay que practicar.<br>B) Tengo que practicar.", "A) Hay que practicar.", "hay que gives a general obligation."),
            ("Hay que yo estudiar.", "Tengo que estudiar.", "Use tener que when naming the person."),
            ("Write in Spanish: You should rest.", "Debes descansar.", "deber + infinitive gives should/must."),
            ("obligation", "tener que / hay que / deber + infinitive", ["Tengo que salir.", "Hay que leer.", "Debemos ayudar."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "quedar vs quedarse",
            "quedar = remain/fit/arrange to meet; quedarse = stay",
            "Use quedar and quedarse in common A2 meanings.",
            ["Quedan dos entradas.", "Me quedo en casa.", "Quedamos a las ocho."],
            "quedarse needs a reflexive pronoun for staying.",
            ("Choose: I am staying at home.<br>A) Quedo en casa.<br>B) Me quedo en casa.", "B) Me quedo en casa.", "staying uses quedarse."),
            ("Quedan en casa esta noche.", "Quedamos en casa esta noche.", "Use quedamos for we arrange to meet."),
            ("Write in Spanish: Two tickets remain.", "Quedan dos entradas.", "quedar agrees with the remaining thing."),
            ("quedar chunk", "quedar/quedarse + complement", ["Queda tiempo.", "Me quedo aquí.", "Quedamos mañana."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "emotion verbs with prepositions",
            "alegrarse de; preocuparse por; tener miedo de",
            "Use common emotion verb-preposition chunks.",
            ["Me alegro de verte.", "Me preocupo por mi familia.", "Tengo miedo de fallar."],
            "Learn the preposition with the expression.",
            ("Choose: I am happy to see you.<br>A) Me alegro de verte.<br>B) Me alegro verte.", "A) Me alegro de verte.", "alegrarse takes de."),
            ("Me preocupo de mi familia.", "Me preocupo por mi familia.", "preocuparse commonly takes por for concern about someone/something."),
            ("Write in Spanish: I am afraid of failing.", "Tengo miedo de fallar.", "tener miedo de + infinitive."),
            ("emotion chunk", "emotion expression + preposition", ["Me alegro de eso.", "Se preocupa por ti.", "Tengo miedo de salir."]),
        ),
        _topic(
            "a0_survival",
            "numbers 0 to 20",
            "cero, uno, dos... veinte",
            "Use small numbers for age, quantity, phone numbers, and basic dates.",
            ["tengo dos libros", "hay tres personas", "uno, dos, tres"],
            "uno changes before masculine nouns: un libro.",
            ("Choose: one book<br>A) uno libro<br>B) un libro", "B) un libro", "uno shortens to un before a masculine singular noun."),
            ("uno libro", "un libro", "Use un before a masculine singular noun."),
            ("Write in Spanish: I have two books.", "Tengo dos libros.", "dos does not change for gender."),
            ("number + noun", "number + plural noun", ["dos libros", "tres casas", "cinco personas"]),
        ),
        _topic(
            "a0_survival",
            "days and months",
            "lunes, martes...; enero, febrero...",
            "Use days and months to make basic time phrases.",
            ["el lunes", "en enero", "hoy es martes"],
            "Days and months are not capitalized in normal Spanish.",
            ("Choose: Monday<br>A) Lunes<br>B) lunes", "B) lunes", "Days are lowercase unless sentence-initial."),
            ("Hoy es Lunes.", "Hoy es lunes.", "Spanish does not normally capitalize days."),
            ("Write in Spanish: Today is Monday.", "Hoy es lunes.", "Use hoy es + day."),
            ("basic date word", "hoy es + day", ["Hoy es martes.", "Mañana es viernes.", "En enero."]),
        ),
        _topic(
            "a0_survival",
            "time basics",
            "Es la una; son las dos/tres...",
            "Use es la for one o'clock and son las for other hours.",
            ["Es la una.", "Son las dos.", "Son las ocho y media."],
            "Do not use son las with una.",
            ("Choose: It is one o'clock.<br>A) Es la una.<br>B) Son las una.", "A) Es la una.", "One o'clock is singular."),
            ("Son las una.", "Es la una.", "Use es la for one o'clock."),
            ("Write in Spanish: It is three o'clock.", "Son las tres.", "Use son las for plural hours."),
            ("telling time", "es la/son las + hour", ["Es la una.", "Son las cuatro.", "Son las seis."]),
        ),
        _topic(
            "a0_survival",
            "basic prepositions",
            "en = in/on/at; a = to; de = of/from; con = with; sin = without",
            "Use core prepositions as small grammar connectors.",
            ["en casa", "a Madrid", "de Ana", "con Luis", "sin azúcar"],
            "English at/in/on often map to Spanish en.",
            ("Choose: I live in Madrid.<br>A) Vivo en Madrid.<br>B) Vivo a Madrid.", "A) Vivo en Madrid.", "Location usually uses en."),
            ("Estoy a casa.", "Estoy en casa.", "Location uses en."),
            ("Write in Spanish: with Ana", "con Ana", "con means with."),
            ("preposition chunk", "preposition + noun", ["en casa", "a la escuela", "con mi amigo"]),
        ),
        _topic(
            "a0_survival",
            "basic word order",
            "subject + verb + object/complement",
            "Use simple Spanish word order before making longer sentences.",
            ["Yo estudio español.", "Ana come pan.", "El libro es bueno."],
            "Spanish allows flexible order, but beginners should start with simple SVO.",
            ("Choose: Ana eats bread.<br>A) Ana come pan.<br>B) Come Ana pan.", "A) Ana come pan.", "Subject + verb + object is the safest basic order."),
            ("Yo español estudio.", "Yo estudio español.", "Keep the basic verb after the subject for beginner sentences."),
            ("Write in Spanish: Ana studies Spanish.", "Ana estudia español.", "Use subject + verb + object."),
            ("simple sentence", "subject + verb + object", ["Yo leo libros.", "Luis bebe agua.", "Ana estudia español."]),
        ),
        _topic(
            "a0_survival",
            "polite phrases",
            "por favor; gracias; perdón; lo siento",
            "Use fixed phrases for basic polite interaction.",
            ["Gracias.", "Por favor.", "Lo siento."],
            "Do not translate every English polite phrase word by word.",
            ("Choose: thank you<br>A) Gracias.<br>B) Por favor.", "A) Gracias.", "Use the gratitude phrase, not the request softener."),
            ("Estoy siento.", "Lo siento.", "Use the fixed apology phrase, not a literal estoy construction."),
            ("Write in Spanish: Please.", "Por favor.", "Use the fixed polite request phrase."),
            ("polite chunk", "fixed phrase", ["Gracias.", "Perdón.", "Por favor."]),
        ),
        _topic(
            "a1_1_foundations",
            "ir present",
            "ir: voy, vas, va, vamos, van",
            "Use ir for movement and with a + infinitive for future plans.",
            ["Voy a casa.", "Vamos al mercado.", "Ella va a estudiar."],
            "Use a after ir when going to a place or before an infinitive plan.",
            ("Choose: I go to school.<br>A) Voy a la escuela.<br>B) Voy la escuela.", "A) Voy a la escuela.", "ir to a place needs a."),
            ("Yo va a casa.", "Yo voy a casa.", "The yo form of ir is voy."),
            ("Write in Spanish: We go to the market.", "Vamos al mercado.", "a + el contracts to al."),
            ("ir + place", "ir + a + place", ["Voy a casa.", "Vas al trabajo.", "Vamos a Madrid."]),
        ),
        _topic(
            "a1_1_foundations",
            "tener present",
            "tener: tengo, tienes, tiene, tenemos, tienen",
            "Use tener for possession, age, and some fixed expressions.",
            ["Tengo un coche.", "Tienes tiempo.", "Ella tiene veinte años."],
            "tener is irregular in the yo form: tengo.",
            ("Choose: I have time.<br>A) Tengo tiempo.<br>B) Teno tiempo.", "A) Tengo tiempo.", "The yo form is tengo."),
            ("Ella tienes un libro.", "Ella tiene un libro.", "Third-person singular is tiene."),
            ("Write in Spanish: You have a house.", "Tienes una casa.", "tú form of tener is tienes."),
            ("tener + noun", "tener conjugated + noun", ["Tengo tiempo.", "Tienes razón.", "Tenemos libros."]),
        ),
        _topic(
            "a1_1_foundations",
            "hacer present",
            "hacer: hago, haces, hace, hacemos, hacen",
            "Use hacer for doing/making and in some weather expressions.",
            ["Hago la tarea.", "Ella hace café.", "Hace frío."],
            "The yo form is hago, not hazo.",
            ("Choose: I do the homework.<br>A) Hago la tarea.<br>B) Hace la tarea.", "A) Hago la tarea.", "yo form of hacer is hago."),
            ("Yo hace café.", "Yo hago café.", "Use hago with yo."),
            ("Write in Spanish: It is cold.", "Hace frío.", "Weather uses hace in this expression."),
            ("hacer chunk", "hacer conjugated + noun", ["Hago ejercicio.", "Haces café.", "Hace calor."]),
        ),
        _topic(
            "a1_1_foundations",
            "querer and poder present",
            "querer: quiero; poder: puedo",
            "Use querer for wanting and poder for being able to/can.",
            ["Quiero agua.", "Puedo estudiar.", "¿Puedes ayudarme?"],
            "After querer/poder, the next verb stays infinitive.",
            ("Choose: I can speak.<br>A) Puedo hablar.<br>B) Puedo hablo.", "A) Puedo hablar.", "After poder, use the infinitive."),
            ("Quiero estudio.", "Quiero estudiar.", "After querer, use the infinitive."),
            ("Write in Spanish: I want to eat.", "Quiero comer.", "querer + infinitive."),
            ("modal-like verb", "querer/poder + infinitive", ["Quiero salir.", "Puedo leer.", "Puedes venir."]),
        ),
        _topic(
            "a1_1_foundations",
            "estar present",
            "estar: estoy, estás, está, estamos, están",
            "Use estar for location, condition, and temporary state.",
            ["Estoy aquí.", "La tienda está cerrada.", "Estamos cansados."],
            "Accent marks distinguish estás/está from other words.",
            ("Choose: You are here.<br>A) Estás aquí.<br>B) Está aquí.", "A) Estás aquí.", "tú form is estás."),
            ("Yo está en casa.", "Yo estoy en casa.", "yo form is estoy."),
            ("Write in Spanish: We are ready.", "Estamos listos.", "nosotros form is estamos."),
            ("estar + state/place", "estar conjugated + place/state", ["Estoy bien.", "Está en casa.", "Están listos."]),
        ),
        _topic(
            "a1_1_foundations",
            "adverbs of frequency",
            "siempre, normalmente, a veces, nunca",
            "Use frequency adverbs to describe routines.",
            ["Siempre estudio.", "A veces trabajo.", "Nunca fumo."],
            "Put no before the verb with nunca if it follows the verb, but beginners can use nunca before the verb.",
            ("Choose: I never drink coffee.<br>A) Nunca bebo café.<br>B) Bebo nunca café.", "A) Nunca bebo café.", "Frequency adverbs often go before the verb."),
            ("Siempre estudio nunca.", "Nunca estudio.", "Use one frequency adverb in a clear position."),
            ("Write in Spanish: I sometimes study at night.", "A veces estudio por la noche.", "a veces means sometimes."),
            ("routine frequency", "frequency word + present verb", ["Siempre leo.", "A veces camino.", "Nunca trabajo los domingos."]),
        ),
        _topic(
            "a1_1_foundations",
            "adjective position basics",
            "noun + adjective; some common adjectives can go before the noun",
            "Put most descriptive adjectives after the noun.",
            ["un libro interesante", "una casa grande", "un buen amigo"],
            "Do not copy English adjective order automatically.",
            ("Choose: an interesting book<br>A) un interesante libro<br>B) un libro interesante", "B) un libro interesante", "Most descriptive adjectives follow the noun."),
            ("una roja casa", "una casa roja", "Color adjectives normally follow the noun."),
            ("Write in Spanish: a big house", "una casa grande", "grande follows the noun in this basic use."),
            ("noun + adjective", "article + noun + adjective", ["un libro nuevo", "una mesa pequeña", "un día difícil"]),
        ),
        _topic(
            "a1_1_foundations",
            "a plus el and de plus el",
            "a + el = al; de + el = del",
            "Use contractions before masculine singular el.",
            ["Voy al banco.", "Vengo del trabajo.", "La puerta del coche."],
            "Do not contract before la, los, or las.",
            ("Choose: I go to the park.<br>A) Voy a el parque.<br>B) Voy al parque.", "B) Voy al parque.", "a + el contracts to al."),
            ("Vengo de el mercado.", "Vengo del mercado.", "de + el contracts to del."),
            ("Write in Spanish: I go to the cinema.", "Voy al cine.", "a + el cine becomes al cine."),
            ("contraction", "al/del + masculine noun", ["al trabajo", "del banco", "al mercado"]),
        ),
        _topic(
            "a1_1_foundations",
            "dates",
            "el + number + de + month",
            "Use Spanish date order: day of month.",
            ["el 5 de mayo", "el 10 de junio", "Hoy es el 3 de abril."],
            "Do not capitalize months.",
            ("Choose: May 5<br>A) el 5 de mayo<br>B) mayo 5", "A) el 5 de mayo", "Spanish dates use day + de + month."),
            ("Hoy es Mayo 5.", "Hoy es el 5 de mayo.", "Use Spanish date order and lowercase month."),
            ("Write in Spanish: Today is June 10.", "Hoy es el 10 de junio.", "Use el + number + de + month."),
            ("date phrase", "el + day + de + month", ["el 2 de enero", "el 14 de febrero", "el 20 de agosto"]),
        ),
        _topic(
            "a1_1_foundations",
            "weather basics",
            "hace + noun; está + adjective; hay + noun",
            "Use fixed weather expressions.",
            ["Hace frío.", "Hace sol.", "Está nublado.", "Hay viento."],
            "Do not translate 'it is' with es for most weather expressions.",
            ("Choose: It is hot.<br>A) Hace calor.<br>B) Es calor.", "A) Hace calor.", "Weather often uses hacer."),
            ("Es frío hoy.", "Hace frío hoy.", "Cold weather uses hace frío."),
            ("Write in Spanish: It is sunny.", "Hace sol.", "Use hace sol."),
            ("weather expression", "hace/está/hay + weather word", ["Hace calor.", "Está lloviendo.", "Hay niebla."]),
        ),
        _topic(
            "a1_2_core_sentences",
            "stem changing e to ie",
            "e -> ie in stressed present forms: querer -> quiero, quieres",
            "Use stem changes for common present-tense verbs.",
            ["Quiero café.", "Tú quieres agua.", "Ella empieza hoy."],
            "nosotros often does not stem-change: queremos.",
            ("Choose: I want coffee.<br>A) Quero café.<br>B) Quiero café.", "B) Quiero café.", "querer changes e to ie in yo."),
            ("Nosotros quieremos comer.", "Nosotros queremos comer.", "nosotros does not stem-change here."),
            ("Write in Spanish: She wants water.", "Ella quiere agua.", "querer changes to quiere."),
            ("e to ie present", "stem change + present ending", ["quiero", "piensas", "empieza"]),
        ),
        _topic(
            "a1_2_core_sentences",
            "stem changing o to ue",
            "o -> ue in stressed present forms: poder -> puedo, dormir -> duermo",
            "Use stem changes for common ability and routine verbs.",
            ["Puedo salir.", "Duermo bien.", "Ella vuelve tarde."],
            "nosotros often does not stem-change: podemos.",
            ("Choose: I can go.<br>A) Puedo ir.<br>B) Podo ir.", "A) Puedo ir.", "poder changes o to ue in yo."),
            ("Nosotros puedemos estudiar.", "Nosotros podemos estudiar.", "nosotros does not stem-change here."),
            ("Write in Spanish: I sleep well.", "Duermo bien.", "dormir changes o to ue in yo."),
            ("o to ue present", "stem change + present ending", ["puedo", "duermes", "vuelve"]),
        ),
        _topic(
            "a1_2_core_sentences",
            "stem changing e to i",
            "e -> i in stressed present forms: pedir -> pido",
            "Use this pattern for common -ir verbs like pedir and servir.",
            ["Pido agua.", "Ella sirve café.", "¿Repites la frase?"],
            "Do not apply the change to every -ir verb.",
            ("Choose: I ask for water.<br>A) Pedo agua.<br>B) Pido agua.", "B) Pido agua.", "pedir changes e to i in yo."),
            ("Ella serve café.", "Ella sirve café.", "servir changes e to i."),
            ("Write in Spanish: I repeat the phrase.", "Repito la frase.", "repetir changes e to i in yo."),
            ("e to i present", "stem change + present ending", ["pido", "sirves", "repite"]),
        ),
        _topic(
            "a1_2_core_sentences",
            "saber vs conocer",
            "saber + dato/infinitivo; conocer + persona/lugar",
            "Use saber for information and conocer for familiarity.",
            ["Sé la respuesta.", "Conozco a Ana.", "Sé nadar."],
            "Use personal a with conocer a + person.",
            ("Choose: I know Ana.<br>A) Sé Ana.<br>B) Conozco a Ana.", "B) Conozco a Ana.", "Knowing a person uses conocer."),
            ("Conozco la respuesta.", "Sé la respuesta.", "Knowing information uses saber."),
            ("Write in Spanish: I know how to swim.", "Sé nadar.", "saber + infinitive means know how to."),
            ("know contrast", "saber + fact/infinitive; conocer + person/place", ["Sé español.", "Conozco Madrid.", "Sé cocinar."]),
        ),
        _topic(
            "a1_2_core_sentences",
            "personal a",
            "a + specific person after many direct-object verbs",
            "Use personal a before a specific person who receives the action.",
            ["Veo a Ana.", "Busco a mi hermano.", "Conozco a Luis."],
            "Do not use personal a before ordinary things.",
            ("Choose: I see Ana.<br>A) Veo Ana.<br>B) Veo a Ana.", "B) Veo a Ana.", "Specific person as object takes personal a."),
            ("Veo a el libro.", "Veo el libro.", "Do not use personal a with things."),
            ("Write in Spanish: I know Luis.", "Conozco a Luis.", "conocer + person uses personal a."),
            ("person as object", "verb + a + person", ["Veo a mi madre.", "Busco a Carlos.", "Ayudo a Ana."]),
        ),
        _topic(
            "a1_2_core_sentences",
            "object pronoun placement",
            "before conjugated verb; attached to infinitive",
            "Place object pronouns before a conjugated verb or attach them to an infinitive.",
            ["Lo quiero.", "Quiero verlo.", "Lo voy a comprar.", "Voy a comprarlo."],
            "Do not place the pronoun randomly after a conjugated verb.",
            ("Choose: I want to see it.<br>A) Quiero verlo.<br>B) Quiero ver lo.", "A) Quiero verlo.", "Pronouns attach directly to infinitives."),
            ("Veo lo.", "Lo veo.", "With a conjugated verb, the object pronoun goes before it."),
            ("Write in Spanish: I am going to buy it. (it = el libro)", "Voy a comprarlo.", "Attach lo to the infinitive."),
            ("pronoun placement", "pronoun + conjugated verb / infinitive+pronoun", ["Lo leo.", "Puedo hacerlo.", "La quiero ver."]),
        ),
        _topic(
            "a1_2_core_sentences",
            "negative words",
            "nada, nadie, nunca, tampoco",
            "Use negative words to say nothing, nobody, never, neither/not either.",
            ["No veo nada.", "Nadie viene.", "Nunca trabajo tarde.", "Yo tampoco."],
            "Spanish often keeps no with a negative word after the verb.",
            ("Choose: I see nothing.<br>A) No veo nada.<br>B) Veo nada.", "A) No veo nada.", "Use no before the verb with nada after it."),
            ("No veo algo.", "No veo nada.", "nada means nothing."),
            ("Write in Spanish: Nobody is here.", "Nadie está aquí.", "nadie means nobody."),
            ("negative word", "no + verb + negative word", ["No tengo nada.", "No conozco a nadie.", "No voy nunca."]),
        ),
        _topic(
            "a1_2_core_sentences",
            "tambien vs tampoco",
            "también = also; tampoco = neither/not either",
            "Use también for agreement with positive statements and tampoco with negative statements.",
            ["Yo también estudio.", "Yo tampoco fumo.", "Ella también viene."],
            "Do not use también to agree with a negative sentence.",
            ("Choose: I don't work today. Me neither.<br>A) Yo también.<br>B) Yo tampoco.", "B) Yo tampoco.", "Use tampoco with negative agreement."),
            ("No tengo tiempo. Yo también.", "No tengo tiempo. Yo tampoco.", "Negative agreement needs tampoco."),
            ("Write in Spanish: I also study.", "Yo también estudio.", "también means also."),
            ("agreement response", "yo también / yo tampoco", ["Yo también.", "Yo tampoco.", "Nosotros también."]),
        ),
        _topic(
            "a1_2_core_sentences",
            "demonstratives",
            "este/esta/estos/estas; ese/esa/esos/esas",
            "Use demonstratives for this/these and that/those.",
            ["este libro", "esta casa", "esos coches", "esas mesas"],
            "Demonstratives agree with the noun.",
            ("Choose: this house<br>A) este casa<br>B) esta casa", "B) esta casa", "casa is feminine singular."),
            ("estos mesa", "estas mesas", "mesa is feminine; plural is mesas."),
            ("Write in Spanish: those books", "esos libros", "libros is masculine plural."),
            ("this/that + noun", "este/esta/ese/esa + noun", ["este café", "esta puerta", "esos días"]),
        ),
        _topic(
            "a1_2_core_sentences",
            "tener expressions",
            "tener hambre/sed/frío/calor/sueño/miedo",
            "Use tener for many physical states that use be in English.",
            ["Tengo hambre.", "Tiene frío.", "Tenemos sueño."],
            "Do not translate I am hungry as estoy hambre.",
            ("Choose: I am hungry.<br>A) Tengo hambre.<br>B) Estoy hambre.", "A) Tengo hambre.", "Spanish uses tener hambre."),
            ("Estoy sed.", "Tengo sed.", "Use tener sed for being thirsty."),
            ("Write in Spanish: We are sleepy.", "Tenemos sueño.", "Use tener sueño."),
            ("tener + state noun", "tener + hambre/sed/frío/calor", ["Tengo frío.", "Tienes miedo.", "Tiene calor."]),
        ),
        _topic(
            "a1_2_core_sentences",
            "acabar de infinitive",
            "acabar de + infinitive",
            "Use acabar de for very recent actions.",
            ["Acabo de llegar.", "Acaba de salir.", "Acabamos de comer."],
            "The second verb stays infinitive.",
            ("Choose: I just arrived.<br>A) Acabo de llegar.<br>B) Acabo de llego.", "A) Acabo de llegar.", "After de, use the infinitive."),
            ("Acaba de salió.", "Acaba de salir.", "Use infinitive after acabar de."),
            ("Write in Spanish: We just ate.", "Acabamos de comer.", "acabar de + infinitive."),
            ("just did", "acabar de + infinitive", ["Acabo de leer.", "Acabas de venir.", "Acaban de llamar."]),
        ),
        _topic(
            "a2_1_daily_past",
            "regular imperfect forms",
            "-ar: aba, abas, aba, ábamos, aban; -er/-ir: ía, ías, ía, íamos, ían",
            "Use imperfect endings for habits and background in the past.",
            ["Hablaba mucho.", "Comíamos juntos.", "Vivían en Perú."],
            "Imperfect yo and él/ella forms are identical.",
            ("Choose: I used to speak.<br>A) Hablé.<br>B) Hablaba.", "B) Hablaba.", "Used to/habit uses imperfect."),
            ("Nosotros comía juntos.", "Nosotros comíamos juntos.", "nosotros -er imperfect is -íamos."),
            ("Write in Spanish: They lived in Peru.", "Vivían en Perú.", "vivir imperfect ellos form is vivían."),
            ("imperfect endings", "stem + aba/ía endings", ["hablaba", "comías", "vivíamos"]),
        ),
        _topic(
            "a2_1_daily_past",
            "ser ir ver imperfect",
            "ser: era; ir: iba; ver: veía",
            "Use the three main irregular imperfect verbs accurately.",
            ["Era tarde.", "Iba al colegio.", "Veíamos la televisión."],
            "iba is imperfect of ir, not preterite.",
            ("Choose: I used to go to school.<br>A) Iba al colegio.<br>B) Fui al colegio.", "A) Iba al colegio.", "Habitual past uses imperfect."),
            ("Yo vía la televisión.", "Yo veía la televisión.", "ver imperfect is veía."),
            ("Write in Spanish: It was difficult.", "Era difícil.", "ser imperfect third-person is era."),
            ("irregular imperfect", "era/iba/veía", ["Era niño.", "Iba a casa.", "Veía el mar."]),
        ),
        _topic(
            "a2_1_daily_past",
            "preterite spelling changes",
            "car -> qué; gar -> gué; zar -> cé in yo preterite",
            "Use spelling changes to preserve pronunciation in the yo preterite.",
            ["busqué", "llegué", "empecé"],
            "These are spelling changes, not new endings for every person.",
            ("Choose: I arrived.<br>A) Llegé.<br>B) Llegué.", "B) Llegué.", "gar changes to gué in yo preterite."),
            ("Yo buscé el libro.", "Yo busqué el libro.", "car changes to qué in yo preterite."),
            ("Write in Spanish: I started yesterday.", "Empecé ayer.", "zar changes to cé."),
            ("yo preterite spelling", "car/gar/zar -> qué/gué/cé", ["busqué", "pagué", "almorcé"]),
        ),
        _topic(
            "a2_1_daily_past",
            "reflexive verbs in the past",
            "reflexive pronoun + preterite/imperfect verb",
            "Keep the reflexive pronoun when speaking about past routines or events.",
            ["Me levanté temprano.", "Se duchaba cada mañana.", "Nos acostamos tarde."],
            "The pronoun still agrees with the subject.",
            ("Choose: I got up early.<br>A) Me levanté temprano.<br>B) Se levanté temprano.", "A) Me levanté temprano.", "yo uses me."),
            ("Yo se desperté tarde.", "Yo me desperté tarde.", "Use me with yo."),
            ("Write in Spanish: She went to bed late.", "Se acostó tarde.", "acostarse is reflexive."),
            ("reflexive past", "pronoun + past verb", ["Me duché.", "Te levantaste.", "Se acostó."]),
        ),
        _topic(
            "a2_1_daily_past",
            "past time expressions",
            "ayer, anoche, la semana pasada, hace dos días",
            "Use time expressions to anchor past-tense choices.",
            ["Ayer trabajé.", "Anoche dormí bien.", "Hace dos días fui al médico."],
            "Finished-time expressions often pair with preterite.",
            ("Choose: last week I traveled.<br>A) La semana pasada viajé.<br>B) La semana pasada viajaba.", "A) La semana pasada viajé.", "A finished trip in a finished time uses preterite."),
            ("Ayer estudio.", "Ayer estudié.", "Ayer needs a past form."),
            ("Write in Spanish: Two days ago I went home.", "Hace dos días fui a casa.", "hace + time + preterite."),
            ("past time anchor", "past expression + preterite", ["Ayer comí.", "Anoche salí.", "El lunes trabajé."]),
        ),
        _topic(
            "a2_1_daily_past",
            "future with present tense",
            "present tense + future time expression",
            "Spanish can use present tense for fixed future plans.",
            ["Mañana trabajo.", "Esta noche cenamos juntos.", "El lunes salgo temprano."],
            "Do not overuse present progressive for planned future.",
            ("Choose: Tomorrow I work.<br>A) Mañana trabajo.<br>B) Mañana estoy trabajando.", "A) Mañana trabajo.", "Simple present can express scheduled future."),
            ("Mañana voy trabajo.", "Mañana trabajo.", "Use present tense or voy a trabajar, not voy trabajo."),
            ("Write in Spanish: Tonight we eat together.", "Esta noche cenamos juntos.", "Present tense can mark a planned future."),
            ("scheduled future", "future time + present verb", ["Mañana salgo.", "El viernes viajo.", "Esta noche estudio."]),
        ),
        _topic(
            "a2_1_daily_past",
            "future with ir a",
            "ir a + infinitive",
            "Use ir a for intentions and near-future plans.",
            ["Voy a llamar.", "Vamos a estudiar.", "Van a venir."],
            "Do not conjugate the infinitive after a.",
            ("Choose: They are going to come.<br>A) Van a venir.<br>B) Van a vienen.", "A) Van a venir.", "Use infinitive after a."),
            ("Voy a llamo mañana.", "Voy a llamar mañana.", "After ir a, use infinitive."),
            ("Write in Spanish: We are going to travel.", "Vamos a viajar.", "vamos a + infinitive."),
            ("planned future", "ir + a + infinitive", ["Voy a comer.", "Vas a leer.", "Vamos a practicar."]),
        ),
        _topic(
            "a2_1_daily_past",
            "superlatives",
            "el/la/los/las más + adjective; el mejor/la mejor",
            "Use superlatives to say the most or best.",
            ["Es el libro más interesante.", "Es la mejor opción.", "Son los más caros."],
            "The article agrees with the noun.",
            ("Choose: the best option<br>A) la mejor opción<br>B) el mejor opción", "A) la mejor opción", "opción is feminine."),
            ("Es la más bueno.", "Es la mejor.", "Use mejor for best."),
            ("Write in Spanish: the most important day", "el día más importante", "día is masculine."),
            ("superlative", "article + más/mejor + noun/adjective", ["el más grande", "la mejor casa", "los más rápidos"]),
        ),
        _topic(
            "a2_1_daily_past",
            "affirmative command pronouns",
            "attach pronouns to affirmative commands",
            "Use attached pronouns with affirmative commands.",
            ["Dímelo.", "Léelo.", "Escríbeme."],
            "Accent marks may be needed to keep stress.",
            ("Choose: Read it.<br>A) Léelo.<br>B) Lo lee.", "A) Léelo.", "Affirmative command attaches the pronoun."),
            ("Lee lo.", "Léelo.", "Attach lo and add accent."),
            ("Write in Spanish: Tell me.", "Dime.", "decir tú command with me is dime."),
            ("command + pronoun", "affirmative command + pronoun", ["Míralo.", "Hazlo.", "Dámelo."]),
        ),
        _topic(
            "a2_1_daily_past",
            "negative commands",
            "no + present subjunctive form for tú commands",
            "Use negative tú commands for telling someone not to do something.",
            ["No hables.", "No comas.", "No escribas."],
            "Negative command forms differ from affirmative commands.",
            ("Choose: Don't speak.<br>A) No habla.<br>B) No hables.", "B) No hables.", "Negative tú command of hablar is no hables."),
            ("No come eso.", "No comas eso.", "Negative tú command of comer is no comas."),
            ("Write in Spanish: Don't write.", "No escribas.", "Use negative tú command form."),
            ("negative command", "no + command form", ["No mires.", "No bebas.", "No salgas."]),
        ),
        _topic(
            "a2_1_daily_past",
            "hace time expressions",
            "hace + time + que + present/past",
            "Use hace expressions to say how long something has been happening or when it happened.",
            ["Hace dos años que estudio español.", "Lo vi hace una semana.", "Hace tres días que estoy aquí."],
            "Word order changes the meaning: hace tiempo que... vs ... hace tiempo.",
            ("Choose: I have studied Spanish for two years.<br>A) Hace dos años que estudio español.<br>B) Estudio español para dos años.", "A) Hace dos años que estudio español.", "Duration until now uses hace + time + que + present."),
            ("Estudio español por dos años.", "Hace dos años que estudio español.", "Use hace...que for ongoing duration."),
            ("Write in Spanish: I saw her a week ago.", "La vi hace una semana.", "hace + time after the event means ago."),
            ("time ago/duration", "hace + time", ["Hace un mes.", "Hace dos días que trabajo.", "Llegué hace una hora."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "lo que",
            "lo que + conjugated clause",
            "Use lo que to refer to an idea, action, or whole clause.",
            ["No entiendo lo que dices.", "Lo que quiero es descansar.", "Haz lo que puedas."],
            "Do not use qué inside a statement where lo que is needed.",
            ("Choose: I don't understand what you say.<br>A) No entiendo qué dices.<br>B) No entiendo lo que dices.", "B) No entiendo lo que dices.", "lo que works as 'what/the thing that' inside a statement."),
            ("No sé lo qué quieres.", "No sé lo que quieres.", "Use lo que, not lo qué."),
            ("Write in Spanish: Do what you can.", "Haz lo que puedas.", "lo que refers to the thing/action."),
            ("lo que clause", "lo que + conjugated verb", ["lo que quiero", "lo que haces", "lo que necesitamos"]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "basic subjunctive triggers",
            "querer/esperar/necesitar + que + subjunctive",
            "Recognize and produce common wish/need clauses.",
            ["Quiero que vengas.", "Espero que estés bien.", "Necesito que me ayudes."],
            "If the subject changes after que, Spanish often uses subjunctive.",
            ("Choose: I want you to come.<br>A) Quiero que vienes.<br>B) Quiero que vengas.", "B) Quiero que vengas.", "querer que triggers subjunctive."),
            ("Espero que estás bien.", "Espero que estés bien.", "esperar que commonly triggers subjunctive."),
            ("Write in Spanish: I need you to help me.", "Necesito que me ayudes.", "necesitar que + subjunctive."),
            ("wish/need clause", "verb + que + subjunctive", ["Quiero que estudies.", "Espero que venga.", "Necesito que llames."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "impersonal se",
            "se + third-person verb",
            "Use impersonal se for general statements like one/people/you in general.",
            ["Se habla español.", "Se vive bien aquí.", "Se come tarde en España."],
            "Do not add a specific subject when using impersonal se.",
            ("Choose: Spanish is spoken here.<br>A) Se habla español aquí.<br>B) Habla español aquí.", "A) Se habla español aquí.", "Impersonal se gives the general/passive meaning."),
            ("Se hablan español.", "Se habla español.", "español as a language here is singular/general."),
            ("Write in Spanish: People eat late here.", "Se come tarde aquí.", "Use se + third-person singular."),
            ("general statement", "se + verb", ["Se dice que...", "Se trabaja mucho.", "Se vive bien."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "passive se",
            "se + third-person verb agreeing with thing",
            "Use passive se to say something is sold/done/used without naming the actor.",
            ["Se venden casas.", "Se busca camarero.", "Se usan tarjetas."],
            "With plural things, the verb is often plural.",
            ("Choose: Houses are sold.<br>A) Se vende casas.<br>B) Se venden casas.", "B) Se venden casas.", "casas is plural, so venden."),
            ("Se vende libros.", "Se venden libros.", "Plural noun needs plural verb in passive se."),
            ("Write in Spanish: Credit cards are accepted.", "Se aceptan tarjetas.", "tarjetas is plural, so aceptan."),
            ("passive se", "se + verb + noun", ["Se alquila piso.", "Se venden coches.", "Se aceptan reservas."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "pronouns with commands",
            "affirmative: attach; negative: before command",
            "Place pronouns differently in affirmative and negative commands.",
            ["Dímelo.", "No me lo digas.", "Hazlo.", "No lo hagas."],
            "Do not attach pronouns to negative commands.",
            ("Choose: Don't tell it to me.<br>A) No dímelo.<br>B) No me lo digas.", "B) No me lo digas.", "Negative commands put pronouns before the verb."),
            ("No hazlo.", "No lo hagas.", "Negative command needs pronoun before the command form."),
            ("Write in Spanish: Do it.", "Hazlo.", "Affirmative command attaches lo."),
            ("command pronoun contrast", "affirmative+pronoun; no + pronoun + command", ["Léelo.", "No lo leas.", "Dámelo."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "preposition plus pronoun",
            "mí, ti, él/ella; conmigo/contigo",
            "Use prepositional pronouns after most prepositions.",
            ["para mí", "sin ti", "con ella", "conmigo", "contigo"],
            "con mí and con ti become conmigo and contigo.",
            ("Choose: with me<br>A) con mí<br>B) conmigo", "B) conmigo", "con + mí becomes conmigo."),
            ("para yo", "para mí", "After para, use mí, not yo."),
            ("Write in Spanish: without you", "sin ti", "After preposition sin, use ti."),
            ("preposition pronoun", "preposition + mí/ti/él/ella", ["para mí", "de ti", "con nosotros"]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "relative quien and que",
            "que for things/people; quien often after preposition or commas for people",
            "Use que as the default relative pronoun and quien for people in specific structures.",
            ["La mujer que vive aquí.", "La persona con quien trabajo.", "Mi hermano, quien vive en Chile, viene mañana."],
            "Do not use quien for ordinary thing nouns.",
            ("Choose: the woman who lives here<br>A) la mujer que vive aquí<br>B) la mujer quien vive aquí", "A) la mujer que vive aquí", "que is the default defining relative."),
            ("El libro quien compré", "El libro que compré", "Use que for things."),
            ("Write in Spanish: the person with whom I work", "la persona con quien trabajo", "quien is common after a preposition for people."),
            ("relative pronoun", "noun + que/quien + clause", ["el coche que compré", "la amiga que llamó", "la persona con quien hablé"]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "aunque indicative vs subjunctive recognition",
            "aunque + indicative = known fact; aunque + subjunctive = hypothetical/unknown",
            "Recognize the basic meaning difference with aunque.",
            ["Aunque llueve, salgo.", "Aunque llueva, salgo.", "Aunque es caro, lo compro."],
            "At A2, focus on recognizing the contrast before overproducing it.",
            ("Choose known fact: Although it is raining, I am going out.<br>A) Aunque llueve, salgo.<br>B) Aunque llueva, salgo.", "A) Aunque llueve, salgo.", "Indicative presents the rain as known."),
            ("Aunque llueve mañana, saldré.", "Aunque llueva mañana, saldré.", "An unknown or hypothetical future concession uses subjunctive after aunque."),
            ("Write in Spanish: Although it is expensive, I buy it.", "Aunque es caro, lo compro.", "Known fact uses indicative."),
            ("concession", "aunque + clause", ["Aunque estoy cansado, estudio.", "Aunque llueve, camino.", "Aunque es difícil, sigo."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "conditional basics",
            "conditional ending: -ía, -ías, -ía, -íamos, -ían",
            "Use conditional for would, polite requests, and hypothetical results.",
            ["Me gustaría un café.", "Yo viajaría más.", "¿Podrías ayudarme?"],
            "Do not use quería for every polite would-like request.",
            ("Choose: I would travel more.<br>A) Viajaría más.<br>B) Viajé más.", "A) Viajaría más.", "would + verb uses conditional."),
            ("Me gusta un café, por favor.", "Me gustaría un café, por favor.", "me gustaría is the polite pattern."),
            ("Write in Spanish: Could you help me?", "¿Podrías ayudarme?", "poder in conditional is podrías."),
            ("would/polite", "infinitive + ía endings", ["Me gustaría...", "Sería bueno.", "Podríamos salir."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "si clauses present future",
            "si + present, present/future/command",
            "Use si for real conditions.",
            ["Si tengo tiempo, voy.", "Si llueve, no salgo.", "Si quieres, llamo."],
            "Do not use future immediately after si in basic real conditions.",
            ("Choose: If I have time, I will go.<br>A) Si tendré tiempo, iré.<br>B) Si tengo tiempo, iré.", "B) Si tengo tiempo, iré.", "Use present after si for real future conditions."),
            ("Si voy a tener tiempo, te llamo.", "Si tengo tiempo, te llamo.", "Use present in the si-clause."),
            ("Write in Spanish: If it rains, I don't go out.", "Si llueve, no salgo.", "si + present, present result."),
            ("real condition", "si + present, result", ["Si puedes, ven.", "Si estudias, mejoras.", "Si tengo dinero, viajo."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "reported speech basics",
            "decir que + clause",
            "Use decir que to report simple statements.",
            ["Dice que está cansada.", "Dijo que no tenía tiempo.", "Ana dice que viene mañana."],
            "For A2, keep reported speech simple and avoid complex tense backshift overload.",
            ("Choose: Ana says that she is coming.<br>A) Ana dice que viene.<br>B) Ana dice viene.", "A) Ana dice que viene.", "Reported statement needs que."),
            ("Dice está cansado.", "Dice que está cansado.", "Use que after dice."),
            ("Write in Spanish: He says he has no time.", "Dice que no tiene tiempo.", "decir que + clause."),
            ("reporting", "decir que + sentence", ["Dice que sí.", "Dijo que no.", "Dicen que es fácil."]),
        ),
        _topic(
            "a2_2_natural_spanish",
            "desde hace duration",
            "desde hace + time = for/since a duration",
            "Use desde hace to say how long something has been true.",
            ["Vivo aquí desde hace dos años.", "Trabajo allí desde hace un mes.", "Estudio español desde hace poco."],
            "Do not translate for + duration with para.",
            ("Choose: I have lived here for two years.<br>A) Vivo aquí desde hace dos años.<br>B) Vivo aquí para dos años.", "A) Vivo aquí desde hace dos años.", "Duration until now uses desde hace."),
            ("Trabajo aquí para tres meses.", "Trabajo aquí desde hace tres meses.", "Use desde hace for ongoing duration."),
            ("Write in Spanish: I study Spanish since recently.", "Estudio español desde hace poco.", "desde hace poco means since recently/for a short time."),
            ("ongoing duration", "present + desde hace + time", ["Vivo aquí desde hace un año.", "Trabajo desde hace poco.", "Te conozco desde hace meses."]),
        ),
    ]
)

# Keep LEVELS summaries in sync with TOPICS; TOPICS is the source of truth for generated cards.
for level in LEVELS:
    level["topics"] = [topic["topic"] for topic in TOPICS if topic["level"] == level["id"]]


CARD_TYPE_LABELS = {
    "rule": "Rule",
    "choose": "Choose",
    "correction": "Correction",
    "production": "Production",
    "pattern": "Mini pattern",
}


def _slug(text):
    return text.replace(" ", "_").replace("/", "_").replace("-", "_").lower()


def _tags(level, topic, card_type):
    return ["spanish_grammar", "grammar_maintenance", level, _slug(topic), card_type]


def _self_grade(card_type):
    if card_type == "rule":
        return "Good = remembered the formula and examples. Hard = remembered one part. Again = could not explain it."
    if card_type == "choose":
        return "Good = chose correctly and knew why. Hard = guessed correctly. Again = chose wrong."
    if card_type == "correction":
        return "Good = fixed it and named the rule. Hard = fixed it only. Again = missed the correction."
    if card_type == "production":
        return "Good = produced the target sentence. Hard = minor gender/accent/ending issue. Again = wrong pattern."
    if card_type == "pattern":
        return "Good = could reuse the pattern with a new word. Hard = recognized only. Again = did not remember it."
    return "Good = confident. Hard = partial. Again = missed it."


def _add(cards, level, topic, card_type, front, answer, explanation, examples=None, common_mistake=""):
    cards.append(
        {
            "source_id": f"{level}::{_slug(topic)}::{card_type}",
            "level": level,
            "topic": topic,
            "card_type": card_type,
            "front": front,
            "answer": answer,
            "explanation": explanation,
            "examples": "<br>".join(f"- {example}" for example in (examples or [])),
            "common_mistake": common_mistake,
            "self_grade": _self_grade(card_type),
            "tags": _tags(level, topic, card_type),
        }
    )


def _build_cards():
    cards = []
    for item in TOPICS:
        level = item["level"]
        topic = item["topic"]
        _add(
            cards,
            level,
            topic,
            "rule",
            f"Rule: {topic}",
            f"<b>Formula</b><br>{item['formula']}<br><br><b>Use</b><br>{item['use']}",
            "Memorize the pattern first; the other cards in this topic make you use it.",
            item["examples"],
            item["trap"],
        )
        choose_front, choose_answer, choose_reason = item["choose"]
        _add(cards, level, topic, "choose", choose_front, choose_answer, choose_reason, item["examples"], item["trap"])
        wrong, right, correction_reason = item["correction"]
        _add(cards, level, topic, "correction", f"Correct this Spanish: {wrong}", right, correction_reason, item["examples"], item["trap"])
        prompt, answer, note = item["production"]
        _add(cards, level, topic, "production", prompt, answer, note, item["examples"], item["trap"])
        pattern_name, pattern_formula, pattern_examples = item["pattern"]
        _add(
            cards,
            level,
            topic,
            "pattern",
            f"Mini pattern: {pattern_name}",
            pattern_formula,
            "This is a reusable sentence chunk. Practice swapping one word at a time.",
            pattern_examples,
            item["trap"],
        )
    return cards


SPANISH_GRAMMAR_CARDS = _build_cards()


def get_cards(level=None, card_type=None):
    result = []
    for card in SPANISH_GRAMMAR_CARDS:
        if level is not None and card["level"] != level:
            continue
        if card_type is not None and card["card_type"] != card_type:
            continue
        result.append({**card, "tags": list(card["tags"])})
    return result


def get_level_summary():
    return [
        {
            "id": level["id"],
            "name": level["name"],
            "goal": level["goal"],
            "topics": list(level["topics"]),
            "card_count": len([card for card in SPANISH_GRAMMAR_CARDS if card["level"] == level["id"]]),
        }
        for level in LEVELS
    ]


def render_tsv(cards):
    header = ["#separator:tab", "#html:true"]
    rows = [
        [
            card["source_id"],
            card["level"],
            card["topic"],
            card["card_type"],
            CARD_TYPE_LABELS[card["card_type"]],
            card["front"],
            card["answer"],
            card["explanation"],
            card["examples"],
            card["common_mistake"],
            card["self_grade"],
            " ".join(card["tags"]),
        ]
        for card in cards
    ]
    with io.StringIO() as output:
        writer = csv.writer(output, delimiter="\t", lineterminator="\n")
        for line in header:
            output.write(f"{line}\n")
        writer.writerow(
            [
                "SourceID",
                "Level",
                "Topic",
                "CardType",
                "CardTypeLabel",
                "Front",
                "Answer",
                "Explanation",
                "Examples",
                "CommonMistake",
                "SelfGrade",
                "Tags",
            ]
        )
        writer.writerows(rows)
        return output.getvalue()


def write_import_files(output_dir="generated/spanish_grammar"):
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    path = output_path / "spanish_grammar_a0_a2.tsv"
    path.write_text(render_tsv(get_cards()), encoding="utf-8")
    return str(path)


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description="Generate A0-A2 Spanish grammar Anki deck TSV.")
    parser.add_argument("--output-dir", default="generated/spanish_grammar", help="Output directory")
    parser.add_argument("--summary", action="store_true", help="Print level/card summary")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    if args.summary:
        for item in get_level_summary():
            print(f"{item['id']}: {item['card_count']} cards")
        print(f"total: {len(get_cards())} cards")
        return 0
    path = write_import_files(args.output_dir)
    print(f"Wrote import file: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
